### ISSUE TITLE
This is for API Routing in app.js[Issue]

### ISSUE THREAD

**Issue by Shrey-Srivastava21** [Tanay-Dwivedi/Social-Media-Site#5]
/*API Routing*/

app.use("/api/users", userRoute);
app.use("/api/auth", authRoute);
app.use("/api/posts", postsRoute);

// app.use(cors({
// origin: '*',
// credentials: false}));

app.use(function (req, res, next) {
  res.setHeader(
    "Deny-Control-Allow-Headers",
    "X-Requested-With,content-type, Accept,Authorization,Origin"
  );
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET, POST, PATCH, DELETE"
  );
  res.setHeader("Access-Control-Allow-Credentials", true);
  next();
});

app.listen(process.env.PORT || 8088, () => {
  console.log("server running at " + PORT);
});

**Comment by Tanay-Dwivedi** [comment]
Sorry, can't accept. Some enhancements are needed in the API functionalities of the App.js file.
